### ISSUE TITLE
Does it mean that the current value is getting higher and higher represents memory leak?

### ISSUE THREAD

**Issue by shangxinbo** [pimlie/node-memwatcher#1]
![image](https://user-images.githubusercontent.com/3213618/55136567-b913a880-5169-11e9-858f-0108b9c8dd77.png)

I got the current wallet is get higher.Does it mean memory leak?

**Comment by pimlie** [comment]
Thats difficult to say without knowing what application you are running, but if there is then its probably a very small one. This almost look like some kind of a counter which is incremented, eg if you do `i++` on a global scope then `i` would get bigger and bigger over time and needs more memory to store.

Whether thats a leak or not is up to you to decide.
